version: '3'

services:
  api:
    build:
      context: .
      dockerfile: dev.dockerfile
    volumes:
      - .:/app/
    ports:
      - 8000:3000
    environment:
      - SECRET_KEY=secretkey

  db:
    image: mongo:3.4
    ports:
      - 8001:27017
