enum SignupState {
  Empty,
  PhoneEntered,
  PhoneValidated,
  PhoneInValid,
  PhoneCodeEntered,  
  PhoneCodeConfirmed,
  PhoneCodeInvalid,
  PswEntered,
  PswValid,
  PswInvalid,
  IdEntered,
  SignedUp,
  SignupFailed,
}