name: barty
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  gradient_app_bar: ^0.1.3
  scoped_model: ^0.3.0
  flutter_secure_storage: ^3.3.1+1
  flutter_map: ^0.8.2
  sliding_up_panel: ^0.3.6
  geolocator: ^5.1.3
  provider: ^4.0.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/image.png
    - assets/images/2.0x/image.png
    - assets/images/3.0x/image.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/Nunito-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 200
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Nunito-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/Nunito-ExtraLightItalic.ttf
          weight: 100
          style: italic