name: Dart CI

on:
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: flutter pub get
      working-directory: ./app
    - name: Run tests
      run: flutter pub run test
      working-directory: ./app
