name: Node.js CI

on:
  push:
    paths: 
      - 'backend/**'
      - '!**/README.md'
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: npm i
        working-directory: ./backend 
      - run: npm run build --if-present
        working-directory: ./backend 
      - run: npm test --if-present
        working-directory: ./backend
        env:
          CI: true
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
